@startuml
start
:教师选择课程和班级;
:填写作业要求与截止时间;
:发布作业;
:学生查看作业;
if (截止前提交?) then (是)
  :保存提交记录;
else (否)
  :标记逾期或拒绝提交;
endif
:教师查看提交列表;
if (需要退回修改?) then (是)
  :退回并填写修改意见;
  :学生重新提交;
else (否)
  :评分并填写评语;
endif
:发布成绩事件;
:通知学生查看结果;
stop
@enduml
