eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:true}
    hostname: ${EUREKA_INSTANCE_HOSTNAME:${spring.application.name}}

spring:
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}
