CREATE TABLE IF NOT EXISTS early_warnings (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    student_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,
    class_id BIGINT NULL,
    teacher_id BIGINT NOT NULL,
    warning_type VARCHAR(50) NOT NULL,
    warning_level VARCHAR(50) NOT NULL,
    warning_message VARCHAR(1000) NOT NULL,
    trigger_date DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    is_resolved BOOLEAN NOT NULL DEFAULT FALSE,
    resolved_by BIGINT NULL,
    resolved_date DATETIME(6) NULL,
    resolved_note VARCHAR(1000) NULL,
    assessment_type VARCHAR(50) NULL,
    related_assessment_id BIGINT NULL,
    student_name VARCHAR(100) NULL,
    course_name VARCHAR(100) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    INDEX idx_early_warnings_student_time (student_id, trigger_date),
    INDEX idx_early_warnings_teacher_status_time (teacher_id, is_resolved, trigger_date),
    INDEX idx_early_warnings_teacher_course (teacher_id, course_id, class_id),
    INDEX idx_early_warnings_course_type_level (course_id, warning_type, warning_level)
);
