spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo

server:
  port: 8888

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: ${EUREKA_PREFER_IP_ADDRESS:false}
    hostname: ${EUREKA_INSTANCE_HOSTNAME:localhost}
    ip-address: ${EUREKA_INSTANCE_IP:127.0.0.1}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      service: ${spring.application.name}
